### PR TITLE
fix(subtitles): Consider `hidden` tracks as active

### PR DESCRIPTION
**Pull request by mister-ben**
## Description
`cuechange` events should be triggered for a track with mode `hidden`. Currently a track is only considered active if its mode is `showing`, cues will not be parsed and no cuechange occurs.

## Specific Changes proposed
Check for `hidden` as well as `showing`.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by gkatsev** [comment]
Hm... I seem to be able to listen to the cuechange even of the 608 track in bipbop with and without this change...

**Comment by gkatsev** [comment]
At least in master, currently.

**Comment by mister-ben** [comment]
That has a default track which starts as `showing`. When you change its mode to `hidden` the cues from the vtt segments which were already parsed still exist on the track and will trigger cuechange. Once you get beyond the end of that range no new cues will be added.

**Comment by gkatsev** [comment]
The 608 track isn't on by default and that's the one I listened to cuechange on.

**Comment by mister-ben** [comment]
Ah, 608. This fixes the vtt segments. With this, they'll behave like the 608 or a remote text track would.

**Comment by mister-ben** [comment]
Shouldn't go stale

**Pull request merged**
