### PR TITLE
Revert "Fix repeated segments issue during bandwidth update"

### PR DESCRIPTION
**Pull request by dzianis-dashkevich**
Reverts videojs/http-streaming#1477

### CODE REVIEW

**Comment by gkatsev** [comment]
fyi, the conventional changelog prefix for revert is `revert:`

**Comment by dzianis-dashkevich** [comment]
> fyi, the conventional changelog prefix for revert is revert:

Thank you! I will update the commit message during the merge. (I created this PR automatically using the GitHub Revert button.)

**Comment by gkatsev** [comment]
TIL. didn't know they had a revert button.

**Review by adrums86 — APPROVED** [review]

**Comment by dzianis-dashkevich** [comment]
Yeah, this one: 
CleanShot 2024-02-20 at 20 15 07@2x

**Pull request merged**
