### PR TITLE
fix: cache aes keys for text tracks (#973)

### PR DESCRIPTION
**Pull request by phloxic**
## Description
So far aes keys for vtt are not cached even when `cacheEncryptionKeys: true`.

## Specific Changes proposed
Call `segmentKey()` if the requested vtt segment includes a key before appending, so key can be cached.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by phloxic** [comment]
Here's [an example](https://phloxic.productions/test/videojs/fix973.html).
In network panel filter URLs with `.key`.
Example [before fix](https://phloxic.productions/test/videojs/cachevttkeys.html).

**Comment by phloxic** [comment]
@gkatsev the fix is easy and works, but right now chances are low that I will time to dive into the testing rabbit hole anytime soon, sorry.

**Comment by phloxic** [comment]
@gkatsev - is the lack of a test blocking this?

**Comment by gkatsev** [comment]
A test would be greatly appreciated!

**Comment by phloxic** [comment]
@gkatsev - I feared as much ;-)
Unfortunately I have no clue how the tests work, especially the media related ones. For instance `test/manifests/subtitles.m3u8` loads `./[0-2].webvtt` which I can't find, probably because they are generated somehow, similarly to the manifests referenced by `test/manifests/master-subtitles.m3u8` ... and at that point I give up because I am getting too embarrased ;-) but mainly because, as much as I'd like to, I simply do not have the time atm to really dig into it. Sorry.

**Review by misteroneill — APPROVED** [review]

**Review by gkatsev — APPROVED** [review]

**Pull request merged**
