### PR TITLE
fix(subtitles): set default property if default and autoselect are both enabled

### PR DESCRIPTION
**Pull request by gkatsev**

### CODE REVIEW

**Comment by gkatsev** [comment]
Looking at https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.1, seems like `propreties.default && properties.autoselect` is the correct way to hint whether something should be chosen.

**Comment by forbesjo** [comment]
LGTM, @gesinger ?

**Comment by gkatsev** [comment]
I can try but I'm not sure I have the time to add tests to this.

**Comment by forbesjo** [comment]
@gkatsev I'm going to add some tests and also make the change for `captions`, unless `default` doesn't apply?

**Comment by gkatsev** [comment]
We can actually tell whether it should be captions or subtitles by which characteristics are enabled. If there are characteristics, particularly the value `public.accessibility.describes-music-and-sound`, it means it's captions and not just subtitles.

**Comment by forbesjo** [comment]
I'm specifically referring to https://github.com/videojs/http-streaming/blob/master/src/media-groups.js#L571

**Comment by gkatsev** [comment]
oh, I see. Yeah, we probably should do that there as well.

**Pull request merged**
