### PR TITLE
Add support for sidx segments

### LINKED ISSUE #162: Request sidx defined segments from DASH SegmentBase streams
The following test file cannot be played in the reference player:

https://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd

### PR DESCRIPTION
**Pull request by omarroth**
## Description
Closes #162.
Requires videojs/mux.js#218

This is a sloppy first pass at adding support for SIDX segments. For some background:

A DASH representation can have a `SegmentBase` which looks like this:
```xml
<BaseURL>German_Forest_Short_Poem_german-de-68s-2-lc-128000bps_seg.mp4</
<SegmentBase indexRange="606-805">
    <Initialization range="0-605"/>
</SegmentBase>
```
The `range` refers to a initialization segment that contains information about the media (codec, framerate, etc). The `indexRange` refers to a SIDX segment which contains byte range indexes for the other segments within the file. Using videojs/mpd-parser, the above example generates a single segment with `byterange: {length: 200, offset 606}` and a `duration` equal to the total duration of the file. 

http-streaming currently will immediately end given the above manifest, as it has no way of adding other segments.

SIDX is specified in ISO/IEC 14496-12.

I am using [this manifest](https://invidio.us/api/manifest/dash/id/YE7VzlLtp-4?local=true).

## Specific Changes proposed
I expect this need to be refactored to fit better within http-streaming. Currently, it:
- Looks to see if a segment is a sidx box (has header `sidx`)
- If it does, set the duration of the sidx segment to 0 and parse it to get a list of `references` (byteranges)
- Add new segments to the current playlist with the given byteranges

Still needs tests.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by ldayananda** [comment]
Thanks for the PR @omarroth! This is a great starting point for fixing #162.

I took a look at what's happening, and there's two problems:
1. the sidx isn't exposed from mpd-parser in a way that VHS can access
2. we need to have VHS request the sidx, parse it with mux.js and then update the playlist with the actual media segments 

Doing the 2nd is non-trivial with the structure of the project, so I wound up starting on an alternative set of PRs. For #1, you can follow https://github.com/videojs/mpd-parser/pull/41 and I'll post a WIP PR for the VHS portion of #2 too. Also, thanks for the mux.js PR!

**Comment by omarroth** [comment]
I expected as such regarding 2, I seem to remember it being mentioned in another issue as well. I appreciate you taking a look!

**Comment by ldayananda** [comment]
Any chance you can provide another manifest to develop against? Looks like the content is unavailable now for the url you provided in the issue and this PR

**Comment by omarroth** [comment]
Closing in favor of #303.

**Pull request closed without merging**
