### PR TITLE
feat: add frameRate property to the representation class.

### PR DESCRIPTION
**Pull request by gjanblaszczyk**
## Description
I would like to display to the user the frame rate value for the currently playing quality level. However, it is not possible because the Representation class doesn't have the frameRate property. 
This PR is related to this https://github.com/videojs/mpd-parser/pull/159
## Specific Changes proposed
Add frameRate property to the Representation class.

## Requirements Checklist
- [X] Feature implemented / Bug fixed
- [X] If necessary, more likely in a feature request than a bug fix
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://jsbin.com/gejugat/edit?html,output))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
I guess this needs to wait for the m3u8-parser and mpd-parser updates.

**Comment by gjanblaszczyk** [comment]
Yes, that's correct.

**Comment by gkatsev** [comment]
Just published m3u8-parser 4.8.0 with this as well as videojs-contrib-quality-levels 2.2.0.

**Comment by gkatsev** [comment]
and mpd-parser 0.22.0 is out too.

**Comment by gjanblaszczyk** [comment]
Thank you. I guess we are one step closer to merging this PR.

**Comment by gkatsev** [comment]
@gjanblaszczyk if you can update this PR with the new (non-major) versions, we can merge this in and release it.

**Review by gkatsev — APPROVED** [review]

**Pull request merged**
